//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 04:35:42 PM BST 
//


package com.mycompany.xsd.employeedetails;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetEmployeeDetailsReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetEmployeeDetailsReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="byDepartmenId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="byDepartmentName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetEmployeeDetailsReq", propOrder = {
    "byDepartmenId",
    "byDepartmentName"
})
public class GetEmployeeDetailsReq {

    protected String byDepartmenId;
    protected String byDepartmentName;

    /**
     * Gets the value of the byDepartmenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getByDepartmenId() {
        return byDepartmenId;
    }

    /**
     * Sets the value of the byDepartmenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setByDepartmenId(String value) {
        this.byDepartmenId = value;
    }

    /**
     * Gets the value of the byDepartmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getByDepartmentName() {
        return byDepartmentName;
    }

    /**
     * Sets the value of the byDepartmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setByDepartmentName(String value) {
        this.byDepartmentName = value;
    }

}
