//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 04:35:42 PM BST 
//


package com.mycompany.xsd.employeedetails;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mycompany.xsd.employeedetails package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetEmployeeDetailsRequest_QNAME = new QName("http://mycompany.com/xsd/EmployeeDetails", "getEmployeeDetailsRequest");
    private final static QName _GetEmployeeDetailsResponse_QNAME = new QName("http://mycompany.com/xsd/EmployeeDetails", "getEmployeeDetailsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mycompany.xsd.employeedetails
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetEmployeeDetailsRequest }
     * 
     */
    public GetEmployeeDetailsRequest createGetEmployeeDetailsRequest() {
        return new GetEmployeeDetailsRequest();
    }

    /**
     * Create an instance of {@link EmployeeDetails }
     * 
     */
    public EmployeeDetails createEmployeeDetails() {
        return new EmployeeDetails();
    }

    /**
     * Create an instance of {@link GetEmployeeDetailsReq }
     * 
     */
    public GetEmployeeDetailsReq createGetEmployeeDetailsReq() {
        return new GetEmployeeDetailsReq();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeDetailsRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetEmployeeDetailsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://mycompany.com/xsd/EmployeeDetails", name = "getEmployeeDetailsRequest")
    public JAXBElement<GetEmployeeDetailsRequest> createGetEmployeeDetailsRequest(GetEmployeeDetailsRequest value) {
        return new JAXBElement<GetEmployeeDetailsRequest>(_GetEmployeeDetailsRequest_QNAME, GetEmployeeDetailsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmployeeDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EmployeeDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://mycompany.com/xsd/EmployeeDetails", name = "getEmployeeDetailsResponse")
    public JAXBElement<EmployeeDetails> createGetEmployeeDetailsResponse(EmployeeDetails value) {
        return new JAXBElement<EmployeeDetails>(_GetEmployeeDetailsResponse_QNAME, EmployeeDetails.class, null, value);
    }

}
